### ISSUE TITLE
Can't get attribute 'Individual'

### ISSUE THREAD

**Issue by szymonk92** [rsteca/sklearn-deap#24]
Trying to test example code on Indian Pima Diabetes dataset in Jupyter notebook 5.0.0, Python 3.6, I'm getting an error. Kernel is busy but no processes are running. Turning on debag mode shows:
...
`File "c:\users\szymon\anaconda3\envs\tensorflow\lib\multiprocessing\queues.py", line 345, in get                          return ForkingPickler.loads(res)                                                                                    AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from 'c:\\users\\szymon\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\deap\\creator.py'>                                                                           File "c:\users\szymon\anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 108, in worker                         task = get()                                                                                        `

**Comment by rsteca** [comment]
Can you give me the code you are using? It will be easier to debug that way

**Comment by szymonk92** [comment]
Sure,
`paramgrid = {"kernel": ["rbf"],
             "C"     : np.logspace(-9, 9, num=25, base=10),
             "gamma" : np.logspace(-9, 9, num=25, base=10)}


from evolutionary_search import EvolutionaryAlgorithmSearchCV
cv = EvolutionaryAlgorithmSearchCV(estimator=SVC(),
                                   params=paramgrid,
                                   scoring="accuracy",
                                   cv=kfold,
                                   verbose=1,
                                   population_size=50,
                                   gene_mutation_prob=0.10,
                                   gene_crossover_prob=0.5,
                                   tournament_size=3,
                                   generations_number=5,
                                   n_jobs=4)
%time cv.fit(X, y)

cv.best_score_, cv.best_params_`

**Comment by rsteca** [comment]
I couldn't reproduce the error. Can you tell me which version of the library are you using? also, which version of deap have you installed? I have never tested it using anaconda, can you try it using pip to see if you still have the problem?

**Comment by szymonk92** [comment]
I have no idea how to check sklearn-deap version, but here are some details:

```
Requirement already satisfied: sklearn-deap in c:\users\szymon\anaconda3\envs\tensorflow\lib\site-packages
Requirement already satisfied: numpy>=1.9.3 in c:\users\szymon\anaconda3\envs\tensorflow\lib\site-packages (from sklearn-deap)
Requirement already satisfied: deap>=1.0.2 in c:\users\szymon\anaconda3\envs\tensorflow\lib\site-packages (from sklearn-deap)
Requirement already satisfied: scikit-learn>=0.18.0 in c:\users\szymon\anaconda3\envs\tensorflow\lib\site-packages (from sklearn-deap)
Requirement already satisfied: scipy>=0.16.0 in c:\users\szymon\anaconda3\envs\tensorflow\lib\site-packages (from sklearn-deap)
```

I have installed this library using pip on anaconda environment.

**Comment by sundisktop** [comment]
I had same problem. Seems like it in n_jobs parameter on Windows system. On Linux all works fine

**Comment by rsteca** [comment]
This should be fixed on version 0.2.2

**Comment by sparo-jack** [comment]
still have the problem
Traceback (most recent call last):
  File "C:\Users\uesr\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\uesr\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\uesr\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\uesr\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from 'C:\\Users\\uesr\\Anaconda3\\lib\\site-packages\\deap\\creator.py'>

package version:
deap-1.2.2 
sklearn-deap-0.2.2
